use protobuf::descriptor::DescriptorProto;
use protobuf::descriptor::EnumDescriptorProto;
use protobuf::descriptor::FieldDescriptorProto;
use protobuf::descriptor::OneofDescriptorProto;

use crate::code_writer::CodeWriter;

use super::Customize;

/// Dynamic callback to customize code generation.
pub trait CustomizeCallback: 'static {
    fn message(&self, message: &DescriptorProto) -> Customize {
        let _ = message;
        Customize::default()
    }

    fn field(&self, field: &FieldDescriptorProto) -> Customize {
        let _ = field;
        Customize::default()
    }

    fn special_field(&self, message: &DescriptorProto, field: &str) -> Customize {
        let _ = (message, field);
        Customize::default()
    }

    fn enumeration(&self, enum_type: &EnumDescriptorProto) -> Customize {
        let _ = enum_type;
        Customize::default()
    }

    fn oneof(&self, oneof: &OneofDescriptorProto) -> Customize {
        let _ = oneof;
        Customize::default()
    }
}

pub(crate) struct CustomizeCallbackDefault;

impl CustomizeCallback for CustomizeCallbackDefault {}

/// Write output that generated by [`CustomizeCallback`].
pub fn write_customize_callback(w: &mut CodeWriter, customize: &Customize) {
    for line in customize.before.iter().flat_map(|s| s.lines()) {
        w.write_line(line);
    }
}
